### ISSUE TITLE
Not very optimized

### ISSUE THREAD

**Issue by TreeOfSelf** [somyk33/TNTQueue#1]
Since this was tagged as "Optimization" on Modrinth, I thought I would chime in and say it really doesn't help much when exploding massive amounts of TNT. If you make a massive cube of TNT, it will still tank the server TPS even with only allowing 3 to explode at a time. It does stop the server from outright crashing. In Paper, for example, you could explode a massive cube of TNT and it won't cause TPS drop it just deals with it in batches. 

The problem seems to be rather than queuing the TNT, you are turning it into an entity and then not letting it explode. But by the time you've made it an entity and have tons of TNT exploding, it still is going to drop TPS. Take a look at how Paper does it if you are interested in improving.

**Comment by somyk33** [comment]
Could you please provide a link to Paper`s tnt optimisation?
I was thinking about not “freezing” tnt, but canceling its spawn. This could be a better way to optimize than it is now. Any thoughts on this?

Actually, I already implemented this. But I don't know how to check if it's better because my server drops tps in any case of exploding bunch of tnt
https://github.com/somykOS/TNTEntityLimiter/releases

**Comment by TreeOfSelf** [comment]
I made one that basically does that, but it also kind of combines the TNT explosion force up to a certain amount

https://github.com/TreeOfSelf/PandaTNTFusion

I actually prefer this to Paper's, because with Paper's it still takes a really long time to explode.

As far as the specifics of how Paper's work, I'm pretty sure all that happens is, TNT explodes, block disappears, but then the actual creation of the TNT primed entity is queued. And only a certain amount of these primed TNT entities can exist at once as it rolls through the queue.
